// <auto-generated />
namespace SmartTree.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCalls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCalls));
        
        string IMigrationMetadata.Id
        {
            get { return "201312211321410_AddCalls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
